# Generated by Django 5.0.6 on 2024-07-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_producto_usuario_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(max_length=30),
        ),
    ]
