# Generated by Django 5.0.6 on 2024-07-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_alter_usuario_email_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='telefono_usuario',
        ),
    ]
