# Generated by Django 5.0.6 on 2024-07-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_rename_telefono_usuario_telefono_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña_usuario',
            new_name='contrasegna_usuario',
        ),
    ]
