# Generated by Django 5.0.7 on 2024-07-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_alter_producto_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
