# Generated by Django 5.0.7 on 2024-07-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0008_registro_productos_registro_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_productos',
            old_name='accion_usuario',
            new_name='accion_usuario_nombre',
        ),
        migrations.AlterField(
            model_name='registro_usuarios',
            name='accion_nombre',
            field=models.CharField(choices=[('agregar', 'Agregar'), ('borrar', 'Borrar'), ('editar', 'Editar'), ('ingresar', 'Ingresar')], default=None, max_length=10, null=True),
        ),
    ]
